require 'active_record/connection_adapters/abstract/database_statements'
require 'active_record/connection_adapters/abstract/schema_statements'

require 'master_slave_adapter/adapter'
require 'master_slave_adapter/instance_methods_generation'
require 'master_slave_adapter/active_record_extensions'